### PR TITLE
Experimental/visual refactoring

### PR DESCRIPTION
**Pull request by OliUmbi**
What I have changed: 
- color scheme / color system 
- school infos
- chat bug

### CODE REVIEW

**Comment by OliUmbi** [comment]
This will maybe introduce breaking changes with colors. But they are easy to fix.

**Review by EricWermelinger — APPROVED** [review]

**Comment by EricWermelinger** [comment]
This one doesn't contain the implementation of the pulling in the chat, right?

**Comment by M1chaCH** [comment]
> This one doesn't contain the implementation of the pulling in the chat, right?

I did not see it

**Review by M1chaCH — APPROVED** [review]
I think that the previous color scheme looked better. Because it brought more life into the application, now it just looks like a default material color scheme. Generally I don't like the close to neon colors.   
In addition to that I don't like the primary light color, it is to close to purple for me, but this could obviously be because of my "perfect" eyes. 🤷‍♂️     

chat & school info: 👍  
classes: Why on earth is it not possible for you to just leave my design?? I purposely made the shadow further down and limited the width. 🤷‍♂️😒 The scale however I do understand because of the overall design. 

If you want you can merge, but I just need to put my opinion here.

**Comment by OliUmbi** [comment]
> 

Yes, that with the class-list I'm sorry. I had changed it and forgot to revert it. But I think the width is better since it scales in different viewports better. (You can change it, I don't have a strong opinion about it)
Regarding the color scheme, I think it's more mass appealing. You are right about it looking like Material, but again mass-appeal and familiarity. 
I will merge it and check for mistakes. After that, I won't make intervene again.

**Pull request merged**
